- name: Copy ui-seqr-service service script
  template:
    src: "{{ service_script_file_name }}.j2"
    dest: "{{ service_script_destination }}/{{ service_script_file_name }}.service"
    owner: ansible
    group: ansible
    mode: 0644

- name: Enable ui-seqr-service service script
  systemd:
    name: ui-seqr-service
    enabled: True

- name: Reboot a machine
  reboot:
