version: "3.9"

services:
    kibana:
        container_name: kibana
        image: gcr.io/seqr-project/kibana:gcloud-prod
        environment: 
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        healthcheck:
            test: bash -c "curl -s kibana:5601 | grep kibana"
            interval: 3s
            timeout: 5s
            retries: 100
        ports:
            - 5601:5601
