#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

CLUSTER_NAME: 'seqr-cluster-prod'
CLUSTER_MACHINE_TYPE: 'n1-highmem-8'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 1

KUBERNETES_VERSION: '1.16.13-gke.401'

CLUSTER_EXTERNAL_IP: '35.194.17.244'
CLUSTER_HOSTNAME: 'seqr.broadinstitute.org'
BASE_URL: 'https://seqr.broadinstitute.org/'

ELASTICSEARCH_SERVICE_EXTERNAL_IP: 10.0.4.61
ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200
ELASTICSEARCH_VERSION: 7.8.1

KIBANA_SERVICE_HOSTNAME: kibana-kb-http

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

SEQR_GIT_BRANCH: 'master'

ENABLE_DATABASE_BACKUPS: true
DATABASE_BACKUP_BUCKET: seqr-backups

GUNICORN_WORKER_THREADS: 20    # number of webserver threads

SEQR_POD_MEMORY_LIMIT: 35Gi
REDIS_POD_MEMORY_LIMIT: 10Gi

# TODO remove in https://github.com/broadinstitute/seqr-private/issues/931
UPLOADED_PEDIGREE_FILE_RECIPIENTS: 'shall@broadinstitute.org,kdelano@broadinstitute.org'

###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: default

DEPLOY_TO: 'gcloud-prod'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'prod'
