#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

CLUSTER_NAME: 'seqr-cluster-prod'
DEFAULT_POOL_MACHINE_TYPE: 'n1-highmem-8'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
DEFAULT_POOL_NUM_NODES: 2

NODE_POOLS:
  es-data-nodes:
    num_nodes: 3
    machine_type: n1-highmem-8
    labels: nodeType=data

KUBERNETES_VERSION: '1.16.15-gke.4300'

CLUSTER_EXTERNAL_IP: '35.194.17.244'
CLUSTER_HOSTNAME: 'seqr.broadinstitute.org'
BASE_URL: 'https://seqr.broadinstitute.org/'

DISKS: postgres, seqr-static-files, es-data

POSTGRES_DISK_SIZE: '200Gb'
SEQR_STATIC_FILES_DISK_SIZE: '50Gb'

ES_DATA_NUM_DISKS: 3
ES_DATA_DISK_TYPE: pd-ssd
ES_DATA_DISK_SIZE: 3200
ES_DATA_SNAPSHOTS:  snp-es-cluster-prod-es-data-disk-1, snp-es-cluster-prod-es-data-disk-2, snp-es-cluster-prod-es-data-disk-3

ELASTICSEARCH_JVM_MEMORY: 22g
ELASTICSEARCH_CONTAINER_MEMORY: 44Gi

ES_DATA_NUM_PODS: 3
ES_CLIENT_NUM_PODS: 3
ES_MASTER_NUM_PODS: 3
ES_LOADING_NUM_PODS: 4

ES_DATA_SERVICE_IP: 10.128.0.52

# when we want to swap to the in-cluster ES, we can uncomment this and remove the below ELASTICSEARCH_SERVICE_ variables
ELASTICSEARCH_SERVICE_HOSTNAME: elasticsearch-es-client
#ELASTICSEARCH_SERVICE_EXTERNAL_IP: 10.0.0.2
#ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200

ELASTICSEARCH_VERSION: 7.8.1

KIBANA_SERVICE_HOSTNAME: kibana-kb-http

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

SEQR_GIT_BRANCH: 'master'

ENABLE_DATABASE_BACKUPS: true
DATABASE_BACKUP_BUCKET: seqr-backups

GUNICORN_WORKER_THREADS: 20    # number of webserver threads

SEQR_POD_MEMORY_LIMIT: 35Gi
REDIS_POD_MEMORY_LIMIT: 10Gi

# TODO remove in https://github.com/broadinstitute/seqr-private/issues/931
UPLOADED_PEDIGREE_FILE_RECIPIENTS: 'shall@broadinstitute.org,kdelano@broadinstitute.org'

LINKERD_VERSION: 'stable-2.9.1'

###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: default

DEPLOY_TO: 'gcloud-prod'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'prod'
