#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

POSTGRES_DISK_SIZE: '200Gb'   # used when creating the GKE cluster on gcloud deployments
SEQR_STATIC_FILES_DISK_SIZE: '50Gb'  # used when creating the GKE cluster on gcloud deployments

DISKS: postgres, seqr-static-files

# This is not used in most deployments so picked 0 as an arbitrary default.
# Because all yamls's are templated on deploy whether or not they are used, it needs to be defined
ES_LOADING_NUM_PODS: 0
ES_DATA_NUM_PODS: 0

NUM_NODES_PER_NODE_POOL: 4    # used when creating nodes for gcloud deployments

GUNICORN_WORKER_THREADS: 4    # number of webserver threads

# this is a security measure to prevent kubectl commands from working unless they are run on a machine with a listed ip address
# this allows cluster administration only from known machines or from machines on google cloud.
MASTER_AUTHORIZED_NETWORKS: '69.173.112.0/21,69.173.127.232/29,69.173.127.128/26,69.173.127.0/25,69.173.127.240/28,69.173.127.224/30,69.173.127.230/31,69.173.120.0/22,69.173.127.228/32,69.173.126.0/24,69.173.96.0/20,69.173.64.0/19,69.173.127.192/27,69.173.124.0/23'

###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

DOCKER_IMAGE_PREFIX: 'gcr.io/seqr-project'
IMAGE_PULL_POLICY: 'Always'

DEPLOYMENT_TEMP_DIR: '/tmp'
DATA_DIR: '/data'
STATIC_MEDIA_DIR: '/seqr_static_files'
MME_CONFIG_DIR: '/mme'

POSTGRES_SERVICE_HOSTNAME: postgres
POSTGRES_USERNAME: postgres
ELASTICSEARCH_SERVICE_HOSTNAME: elasticsearch
KIBANA_SERVICE_HOSTNAME: kibana
REDIS_SERVICE_HOSTNAME: redis

COCKPIT_SERVICE_PORT: 9090
POSTGRES_SERVICE_PORT: 5432
ELASTICSEARCH_SERVICE_PORT: 9200
KIBANA_SERVICE_PORT: 5601
SEQR_SERVICE_PORT: 8000
REDIS_SERVICE_PORT: 6379
PIPELINE_RUNNER_SERVICE_PORT: 30005

SEQR_UI_DEV_PORT: 3000


